site:
  title: OpenCPN Manuals
  url: https://opencpn-manuals.github.io/plugins
  start_page:  opencpn-plugins::index.adoc

content:
  sources:
    - url: .
      branches: HEAD
      start_paths:
      - manual/master-plugins
      - manual/beta-plugins

    - url: sources/aisradar_pi/
      branches: HEAD
      start_path: manual/ais_radar_display

    - url: sources/DR_pi
      branches: HEAD
      start_path: manual/dead_reckoning

    - url: sources/EngineDashboard
      start_path: manual
      branches: HEAD
      edit_url: https://github.com/opencpn-manuals/EngineDashboard/edit/master/{path}


    - url: sources/EarthExplorer_pi
      branches: HEAD
      start_path: manual/earthexplorer

    - url: sources/oesenc_pi
      branches: HEAD
      start_path: manual
      edit_url: https://github.com/leamas/oesenc_pi/edit/master/{path}

    - url: sources/otcurrent_pi
      branches: HEAD
      start_path: manual/otcurrent

    - url: sources/otidalplan_pi
      branches: HEAD
      start_path: manual/otidalplan

    - url: sources/otidalroute_pi
      branches: HEAD
      start_path: manual/otidalroute

    - url: sources/photolayer_pi
      branches: HEAD
      start_path: manual/photolayer

    - url: sources/radar_pi
      branches: HEAD
      start_path: manual/radar

    - url: sources/SailawayNMEA_pi
      branches: HEAD
      start_path: manual/sailawaynmea

    - url: sources/sar_pi
      branches: HEAD
      start_path: manual/sar

    - url: sources/shipdriver_pi
      branches: HEAD
      start_path: manual/shipdriver

    - url: sources/survey_pi
      branches: HEAD
      start_path: manual/survey

    - url: sources/TideFinder_pi/
      branches: HEAD
      start_path: manual/tidefinder

    - url: sources/TwoCanPlugIn
      start_path: manual
      branches: HEAD
      edit_url: https://github.com/opencpn-manuals/TwoCanPlugIn/edit/master/{path}

    - url: sources/UKTides_pi
      branches: HEAD
      start_path: manual/uktides

    - url: sources/vfkaps_pi
      branches: HEAD
      start_path: manual/vfkaps

    - url: sources/watchdog_pi/
      branches: HEAD
      start_path: manual/watchdog
      
    - url: sources/chartscale_pi
      branches: HEAD
      start_path: manual/chartscale
    
    - url: sources/objsearch_pi/
      branches: HEAD
      start_path: manual/objsearch

    - url: sources/vdr_pi
      branches: HEAD
      start_path: manual/vdr
    

ui:
  bundle:
    url: ./ui-bundle.zip
    snapshot: true
  supplemental_files:
    - path: ui.yml
      contents: |
        static_files: [ .nojekyll ]
    - path: .nojekyll

output:
  dir: docs
  clean: true

asciidoc:
  attributes:
    page-resource_1_title: OpenCPN.org
    page-resource_1_url: https://www.opencpn.org/
    page-resource_2_title: User Manual
    page-resource_2_url: https://opencpn.org/wiki/dokuwiki/doku.php?id=opencpn:opencpn_user_manual
    page-resource_3_title: Github Site
    page-resource_3_url: https://github.com/opencpn/OpenCPN
    page-resource_4_title: Bugtracker
    page-resource_4_url: https://opencpn.org/flyspray/
    page-resource_5_title: Plugin Manual (WIP)
    page-resource_5_url: https://opencpn-manuals.github.io/plugins/
