site:
  title: OpenCPN Manuals
  url: https://opencpn-manuals.github.io/plugins
  start_page:  opencpn-plugins::index.adoc

content:
  sources:
    - url: .
      branches: HEAD
      edit_url: true
      start_paths:
      - manual/master-plugins
      - manual/beta-plugins
    
    - url: .
      branches: HEAD
      start_path: ./sources/DR_pi/manual/dead_reckoning
    
    - url: .
      branches: HEAD
      start_path: ./sources/EarthExplorer_pi/manual/earthexplorer
    
    - url: .
      branches: HEAD
      start_path: ./sources/otcurrent_pi/manual/otcurrent
    
    - url: .
      branches: HEAD
      start_path: ./sources/otidalplan_pi/manual/otidalplan
    
    - url: .
      branches: HEAD
      start_path: ./sources/otidalroute_pi/manual/otidalroute
    
    - url: .
      branches: HEAD
      start_path: ./sources/photolayer_pi/manual/photolayer
    
    - url: .
      branches: HEAD
      start_path: ./sources/SailawayNMEA_pi/manual/sailawaynmea
    
    - url: .
      branches: HEAD
      start_path: ./sources/sar_pi/manual/sar
    
    - url: .
      branches: HEAD
      start_path: ./sources/shipdriver_pi/manual/shipdriver
    
   - url: .
      branches: HEAD
      start_path: ./sources/survey_pi/manual/survey
    
  - url: .
      branches: HEAD
      start_path: ./sources/TideFinder_pi/manual/tidefinder
    
   - url: .
      branches: HEAD
      start_path: ./sources/UKTides_pi/manual/uktides
    
   - url: .
      branches: HEAD
      start_path: ./sources/vfkaps_pi/manual/vfkaps

ui:
  bundle:
    url: ./ui-bundle.zip
    snapshot: true
  supplemental_files:
    - path: ui.yml
      contents: |
        static_files: [ .nojekyll ]
    - path: .nojekyll   

output:
  dir: docs
  clean: true

asciidoc:
  attributes:
    page-resource_1_title: OpenCPN.org
    page-resource_1_url: https://www.opencpn.org/
    page-resource_2_title: User Manual
    page-resource_2_url: https://opencpn.org/wiki/dokuwiki/doku.php?id=opencpn:opencpn_user_manual
    page-resource_3_title: Github Site
    page-resource_3_url: https://github.com/opencpn/OpenCPN
    page-resource_4_title: Bugtracker
    page-resource_4_url: https://opencpn.org/flyspray/
    page-resource_5_title: Plugin Manual (WIP)
    page-resource_5_url: https://opencpn-manuals.github.io/plugins/
